# General Jekyll Config
highlighter: pygments
url: http://example.com
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore]

# Theme customization - please change from the defaults!
my_theme:
  # Color for top bar, links, etc
  highlight_color: '#3498db'

  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: grant-olson
  #  twitter: _swanson
  #  hacker_news: swanson

  # "Hi, I'm _______"
  name: Grant T. Olson
  tagline: "WHERE DOES TAGLINGE SHOW???"

  # Google Analytics key, leave blank to ignore
  # google_analytics_key: UA-xxxx-x

  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: false
